import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getMockData } from '../services';
import { statuses, statusLabels, useBoardStore } from '../stores';

const palette = ['#9284f0','#e5a43f','#4c9ae9','#39b97c'];
export default function AnalyticsPage() {
  const tasks=useBoardStore((state)=>state.tasks); const {data}=useQuery({queryKey:['mock-data'],queryFn:getMockData});
  const analytics=useMemo(()=>{
    const all=data?.tasks||tasks;
    const velocity=(data?.sprints||[]).map((sprint)=>({name:sprint.name,completed:all.filter((task)=>task.sprintId===sprint.id&&task.status==='done').length,total:all.filter((task)=>task.sprintId===sprint.id).length}));
    const status=statuses.map((key)=>({name:statusLabels[key],value:tasks.filter((task)=>task.status===key).length}));
    const priorities=['high','medium','low'].map((priority)=>({name:priority[0].toUpperCase()+priority.slice(1),Backlog:tasks.filter((t)=>t.priority===priority&&t.status==='backlog').length,'In progress':tasks.filter((t)=>t.priority===priority&&t.status==='in-progress').length,Review:tasks.filter((t)=>t.priority===priority&&t.status==='review').length,Done:tasks.filter((t)=>t.priority===priority&&t.status==='done').length}));
    const completed=all.filter((task)=>task.completedAt).sort((a,b)=>a.completedAt!.localeCompare(b.completedAt!)); let running=0; const trend=completed.map((task)=>({date:new Date(task.completedAt!).toLocaleDateString('en-US',{month:'short',day:'numeric'}),completed:++running}));
    return {velocity,status,priorities,trend};
  },[data,tasks]);
  const completion=tasks.length?Math.round(tasks.filter((t)=>t.status==='done').length/tasks.length*100):0;
  return <section className="content-page analytics-page"><div className="welcome-heading"><div><span className="eyebrow">LIVE BOARD DATA</span><h1>Sprint analytics</h1><p>Understand pace, workload and where work is getting stuck.</p></div><div className="analytics-score"><strong>{completion}%</strong><span>completion rate</span></div></div><div className="chart-grid"><article className="panel"><header><div><span className="eyebrow">DELIVERY</span><h2>Sprint velocity</h2><p>Completed tasks per sprint</p></div></header><ResponsiveContainer width="100%" height={250}><BarChart data={analytics.velocity}><CartesianGrid vertical={false} stroke="#ececf2"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} width={25}/><Tooltip/><Legend/><Bar dataKey="completed" fill="#6657e8" radius={[6,6,0,0]}/><Bar dataKey="total" fill="#dcd9f7" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article><article className="panel"><header><div><span className="eyebrow">WORKFLOW</span><h2>Task status</h2><p>Current distribution across columns</p></div></header><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={analytics.status} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={3}>{analytics.status.map((_,index)=><Cell key={index} fill={palette[index]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></article><article className="panel"><header><div><span className="eyebrow">RISK</span><h2>Priority breakdown</h2><p>Priority mix across each workflow state</p></div></header><ResponsiveContainer width="100%" height={270}><BarChart data={analytics.priorities}><CartesianGrid vertical={false} stroke="#ececf2"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} width={25}/><Tooltip/><Legend/><Bar dataKey="Backlog" stackId="a" fill={palette[0]}/><Bar dataKey="In progress" stackId="a" fill={palette[1]}/><Bar dataKey="Review" stackId="a" fill={palette[2]}/><Bar dataKey="Done" stackId="a" fill={palette[3]} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article><article className="panel"><header><div><span className="eyebrow">MOMENTUM</span><h2>Completion trend</h2><p>Cumulative work completed over time</p></div></header><ResponsiveContainer width="100%" height={270}><AreaChart data={analytics.trend}><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#6657e8" stopOpacity=".35"/><stop offset="1" stopColor="#6657e8" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#ececf2"/><XAxis dataKey="date" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} width={25}/><Tooltip/><Area type="monotone" dataKey="completed" stroke="#6657e8" fill="url(#area)" strokeWidth={3}/></AreaChart></ResponsiveContainer></article></div></section>;
}
